In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
links=pd.read_csv('links.csv')

In [4]:
movies = pd.read_csv('movies.csv')

In [5]:
ratings=pd.read_csv('ratings.csv')

In [6]:
tags=pd.read_csv('tags.csv')

## Формирование общего рейтинга фильмов

In [8]:
movies_and_ratings = movies.join(ratings.set_index('movieId'), on='movieId')

In [9]:
movies_and_ratings.groupby('title')[['rating']].mean().sort_values(by='rating')

                                             rating
title
Gena the Crocodile (1969)                       5.0
True Stories (1986)                             5.0
Cosmic Scrat-tastrophe (2015)                   5.0
Love and Pigeons (1985)                         5.0
Red Sorghum (Hong gao liang) (1987)             5.0
...                                             ...
Road Home, The (Wo de fu qin mu qin) (1999)     NaN
Roaring Twenties, The (1939)                    NaN
Scrooge (1970)                                  NaN
This Gun for Hire (1942)                        NaN
Twentieth Century (1934)                        NaN

[9737 rows x 1 columns]

In [10]:
ratings_sum = movies_and_ratings.groupby('title')[['rating']].sum()
ratings_sum

                                           rating
title
'71 (2014)                                    4.0
'Hellboy': The Seeds of Creation (2004)       4.0
'Round Midnight (1986)                        7.0
'Salem's Lot (2004)                           5.0
'Til There Was You (1997)                     8.0
...                                           ...
eXistenZ (1999)                              85.0
xXx (2002)                                   66.5
xXx: State of the Union (2005)               10.0
¡Three Amigos! (1986)                        81.5
À nous la liberté (Freedom for Us) (1931)     1.0

[9737 rows x 1 columns]

In [11]:
movies_and_tags = movies.join(tags.set_index('movieId'), on='movieId')
movies_and_tags.head(10)

,movieId,title,genres,userId,tag,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,336.0,pixar,1.139046e+09
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,474.0,pixar,1.137207e+09
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,567.0,fun,1.525286e+09
1,2,Jumanji (1995),Adventure|Children|Fantasy,62.0,fantasy,1.528844e+09
1,2,Jumanji (1995),Adventure|Children|Fantasy,62.0,magic board game,1.528844e+09
1,2,Jumanji (1995),Adventure|Children|Fantasy,62.0,Robin Williams,1.528844e+09
1,2,Jumanji (1995),Adventure|Children|Fantasy,474.0,game,1.137376e+09
2,3,Grumpier Old Men (1995),Comedy|Romance,289.0,moldy,1.143425e+09
2,3,Grumpier Old Men (1995),Comedy|Romance,289.0,old,1.143425e+09
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,NaN,NaN,NaN

In [26]:
tags_count = movies_and_tags.groupby('title')[['tag']].count()
tags_count ['tag'] = tags_count ['tag'] + 1
tags_count

                                           tag
title
'71 (2014)                                   1
'Hellboy': The Seeds of Creation (2004)      1
'Round Midnight (1986)                       1
'Salem's Lot (2004)                          1
'Til There Was You (1997)                    1
...                                        ...
eXistenZ (1999)                              2
xXx (2002)                                   1
xXx: State of the Union (2005)               1
¡Three Amigos! (1986)                        1
À nous la liberté (Freedom for Us) (1931)    1

[9737 rows x 1 columns]

## Формирование рейтинга фильмов в жанре Action

In [22]:
Action = movies_and_ratings[movies_and_ratings['genres'] == 'Action']
Comedy = movies_and_ratings[movies_and_ratings['genres'] == 'Comedy']
Action

      movieId                     title  genres  userId  rating     timestamp
8           9       Sudden Death (1995)  Action   151.0     4.0  8.559474e+08
8           9       Sudden Death (1995)  Action   179.0     3.0  8.521142e+08
8           9       Sudden Death (1995)  Action   217.0     3.0  9.559412e+08
8           9       Sudden Death (1995)  Action   269.0     2.0  8.508656e+08
8           9       Sudden Death (1995)  Action   270.0     3.0  8.539189e+08
...       ...                       ...     ...     ...     ...           ...
9328   160438       Jason Bourne (2016)  Action   586.0     5.0  1.529900e+09
9328   160438       Jason Bourne (2016)  Action   596.0     3.5  1.535710e+09
9339   160684          Marauders (2016)  Action   318.0     3.5  1.484773e+09
9354   161290  Vigilante Diaries (2016)  Action   448.0     1.0  1.498588e+09
9615   176935           Geostorm (2017)  Action   380.0     2.0  1.536873e+09

[186 rows x 6 columns]

In [27]:
ratings_sum = Action.groupby('title')[['rating']].sum().sort_values(by='rating',ascending=False)
ratings_mean = Action.groupby('title')[['rating']].mean().sort_values(by='rating',ascending=False)
ratings_sum
ratings_mean

                                                      rating
title
Knock Off (1998)                                    5.000000
Master of the Flying Guillotine (Du bi quan wan...  4.500000
Big Bird Cage, The (1972)                           4.500000
Game of Death (1978)                                4.166667
Crows Zero (Kurôzu zero) (2007)                     4.000000
Masked Avengers (1981)                              4.000000
Live Wire (1992)                                    4.000000
Ip Man 3 (2015)                                     4.000000
Invincible Shaolin (1978)                           4.000000
Double Team (1997)                                  4.000000
13 Assassins (Jûsan-nin no shikaku) (2010)          4.000000
Kiss of the Dragon (2001)                           3.777778
Rapid Fire (1992)                                   3.750000
Aspen Extreme (1993)                                3.500000
Five Deadly Venoms (1978)                           3.500000
Never Back Down (2008)                              3.500000
Gauntlet, The (1977)                                3.500000
Five Element Ninjas (1982)                          3.500000
Dragon Lord (a.k.a. Dragon Strike) (Long Xiao Y...  3.500000
Marauders (2016)                                    3.500000
Raw Deal (1986)                                     3.333333
Thunderbolt and Lightfoot (1974)                    3.333333
Double Impact (1991)                                3.250000
Minnie and Moskowitz (1971)                         3.250000
Sudden Death (1995)                                 3.125000
Only the Strong (1993)                              3.000000
Once Upon a Time in China III (Wong Fei-hung ts...  3.000000
Octagon, The (1980)                                 3.000000
Walking Tall (2004)                                 3.000000
Hunted, The (1995)                                  3.000000
Ip Man 2 (2010)                                     3.000000
Bloodsport (1988)                                   2.944444
Bloodsport 2 (a.k.a. Bloodsport II: The Next Ku...  2.812500
Last Castle, The (2001)                             2.812500
Jason Bourne (2016)                                 2.722222
Under Siege 2: Dark Territory (1995)                2.716667
Red Heat (1988)                                     2.666667
Tournament, The (2009)                              2.500000
The Crew (2016)                                     2.500000
Big Doll House, The (1971)                          2.500000
Reign of Assassins (2010)                           2.500000
Best of the Best 3: No Turning Back (1995)          2.500000
Kickboxer (1989)                                    2.500000
Avalanche (1978)                                    2.500000
Attila (Attila Flagello di Dio) (1982)              2.500000
Best of the Best (1989)                             2.500000
Punisher, The (1989)                                2.333333
Steel (1997)                                        2.333333
Aces: Iron Eagle III (1992)                         2.000000
Tornado! (1996)                                     2.000000
Delta Force, The (1986)                             2.000000
Geostorm (2017)                                     2.000000
Omega Code, The (1999)                              2.000000
Fair Game (1995)                                    1.700000
American Heist (2015)                               1.500000
No Holds Barred (1989)                              1.000000
Tracers (2015)                                      1.000000
Vigilante Diaries (2016)                            1.000000
Peacekeeper, The (1997)                             1.000000
Lionheart (1990)                                    0.500000

In [28]:
Result_Action = ratings_sum.join(tags_count)
Result_Action

                                                    rating  tag
title
Under Siege 2: Dark Territory (1995)                  81.5    1
Sudden Death (1995)                                   50.0    1
Kiss of the Dragon (2001)                             34.0    1
Bloodsport (1988)                                     26.5    1
Jason Bourne (2016)                                   24.5    1
Last Castle, The (2001)                               22.5    1
Bloodsport 2 (a.k.a. Bloodsport II: The Next Ku...    22.5    1
Walking Tall (2004)                                   18.0    1
13 Assassins (Jûsan-nin no shikaku) (2010)            16.0    1
Ip Man 2 (2010)                                       15.0    1
Game of Death (1978)                                  12.5    1
Double Team (1997)                                    12.0    1
Thunderbolt and Lightfoot (1974)                      10.0    1
Raw Deal (1986)                                       10.0    1
Hunted, The (1995)                                     9.0    1
Fair Game (1995)                                       8.5    1
Crows Zero (Kurôzu zero) (2007)                        8.0    1
Red Heat (1988)                                        8.0    1
Avalanche (1978)                                       7.5    1
Rapid Fire (1992)                                      7.5    1
Punisher, The (1989)                                   7.0    1
Steel (1997)                                           7.0    1
Gauntlet, The (1977)                                   7.0    1
Minnie and Moskowitz (1971)                            6.5    1
Double Impact (1991)                                   6.5    1
Aces: Iron Eagle III (1992)                            6.0    1
Only the Strong (1993)                                 6.0    1
Once Upon a Time in China III (Wong Fei-hung ts...     6.0    1
Best of the Best 3: No Turning Back (1995)             5.0    1
Knock Off (1998)                                       5.0    1
Big Bird Cage, The (1972)                              4.5    1
Master of the Flying Guillotine (Du bi quan wan...     4.5    1
Invincible Shaolin (1978)                              4.0    1
Ip Man 3 (2015)                                        4.0    1
Live Wire (1992)                                       4.0    1
Masked Avengers (1981)                                 4.0    1
Never Back Down (2008)                                 3.5    1
Aspen Extreme (1993)                                   3.5    1
Marauders (2016)                                       3.5    1
Five Element Ninjas (1982)                             3.5    1
Dragon Lord (a.k.a. Dragon Strike) (Long Xiao Y...     3.5    1
Five Deadly Venoms (1978)                              3.5    1
Octagon, The (1980)                                    3.0    1
Reign of Assassins (2010)                              2.5    1
Tournament, The (2009)                                 2.5    1
The Crew (2016)                                        2.5    1
Big Doll House, The (1971)                             2.5    1
Best of the Best (1989)                                2.5    1
Kickboxer (1989)                                       2.5    1
Attila (Attila Flagello di Dio) (1982)                 2.5    1
Geostorm (2017)                                        2.0    1
Delta Force, The (1986)                                2.0    1
Tornado! (1996)                                        2.0    1
Omega Code, The (1999)                                 2.0    1
American Heist (2015)                                  1.5    1
Peacekeeper, The (1997)                                1.0    1
Tracers (2015)                                         1.0    1
Vigilante Diaries (2016)                               1.0    1
No Holds Barred (1989)                                 1.0    1
Lionheart (1990)                                       0.5    1

In [29]:
Result_Action ['res'] = Result_Action ['rating'] * Result_Action ['tag']

In [31]:
Result_Action.sort_values(by='res',ascending=False).head(20)

                                                    rating  tag   res
title
Under Siege 2: Dark Territory (1995)                  81.5    1  81.5
Sudden Death (1995)                                   50.0    1  50.0
Kiss of the Dragon (2001)                             34.0    1  34.0
Bloodsport (1988)                                     26.5    1  26.5
Jason Bourne (2016)                                   24.5    1  24.5
Last Castle, The (2001)                               22.5    1  22.5
Bloodsport 2 (a.k.a. Bloodsport II: The Next Ku...    22.5    1  22.5
Walking Tall (2004)                                   18.0    1  18.0
13 Assassins (Jûsan-nin no shikaku) (2010)            16.0    1  16.0
Ip Man 2 (2010)                                       15.0    1  15.0
Game of Death (1978)                                  12.5    1  12.5
Double Team (1997)                                    12.0    1  12.0
Thunderbolt and Lightfoot (1974)                      10.0    1  10.0
Raw Deal (1986)                                       10.0    1  10.0
Hunted, The (1995)                                     9.0    1   9.0
Fair Game (1995)                                       8.5    1   8.5
Red Heat (1988)                                        8.0    1   8.0
Crows Zero (Kurôzu zero) (2007)                        8.0    1   8.0
Avalanche (1978)                                       7.5    1   7.5
Rapid Fire (1992)                                      7.5    1   7.5

## Формирование рейтинга фильмов в жанре Comedy

In [33]:
ratings_sum1 = Comedy.groupby('title')[['rating']].sum().sort_values(by='rating',ascending=False)
ratings_sum1

                                                    rating
title
Ace Ventura: Pet Detective (1994)                    489.5
Ferris Bueller's Day Off (1986)                      418.5
Clerks (1994)                                        401.0
Monty Python's Life of Brian (1979)                  349.5
Happy Gilmore (1996)                                 340.5
...                                                    ...
Secret Society (2002)                                  0.5
Brothers Solomon, The (2007)                           0.5
Uncle Nino (2003)                                      0.5
Maria Bamford: The Special Special Special! (2012)     0.5
Twentieth Century (1934)                               0.0

[946 rows x 1 columns]

In [36]:
Result_Comedy = ratings_sum1.join(tags_count)
Result_Comedy

                                                    rating  tag
title
Ace Ventura: Pet Detective (1994)                    489.5    1
Ferris Bueller's Day Off (1986)                      418.5    2
Clerks (1994)                                        401.0    7
Monty Python's Life of Brian (1979)                  349.5    4
Happy Gilmore (1996)                                 340.5    4
...                                                    ...  ...
Secret Society (2002)                                  0.5    1
Brothers Solomon, The (2007)                           0.5    1
Uncle Nino (2003)                                      0.5    1
Maria Bamford: The Special Special Special! (2012)     0.5    1
Twentieth Century (1934)                               0.0    2

[946 rows x 2 columns]

In [37]:
Result_Comedy ['res'] = Result_Comedy ['rating'] * Result_Comedy ['tag']

In [38]:
Result_Comedy.sort_values(by='res',ascending=False).head(20)

                                              rating  tag     res
title
Clerks (1994)                                  401.0    7  2807.0
Anchorman: The Legend of Ron Burgundy (2004)   215.0    8  1720.0
Superbad (2007)                                212.5    8  1700.0
Monty Python's Life of Brian (1979)            349.5    4  1398.0
Happy Gilmore (1996)                           340.5    4  1362.0
Zoolander (2001)                               189.5    7  1326.5
This Is Spinal Tap (1984)                      265.0    5  1325.0
Airplane! (1980)                               335.5    3  1006.5
Meet the Parents (2000)                        311.0    3   933.0
Step Brothers (2008)                            99.5    9   895.5
Ferris Bueller's Day Off (1986)                418.5    2   837.0
Mean Girls (2004)                              146.5    5   732.5
Animal House (1978)                            229.0    3   687.0
Billy Madison (1995)                           163.0    4   652.0
Best in Show (2000)                            195.5    3   586.5
I Love You, Man (2009)                          60.0    9   540.0
Ace Ventura: Pet Detective (1994)              489.5    1   489.5
Raising Arizona (1987)                         231.5    2   463.0
Father of the Bride Part II (1995)             150.5    3   451.5
Liar Liar (1997)                               224.5    2   449.0